### ISSUE TITLE
seems can not handle file that has "avro" in the file name

### ISSUE THREAD

**Issue by BorisDaich** [benwatson528/intellij-avro-parquet-plugin#101]
Windows 10 
idea 2022.2 ultimate 
here is sample file
[sample_avro_parquet_files.zip](https://github.com/benwatson528/intellij-avro-parquet-plugin/files/9873830/sample_avro_parquet_files.zip)

**Comment by benwatson528** [comment]
IIRC the code checks for avro/parquet in the filename. I will change it to
an endsWith. I will try to get this done this weekend. Thanks!

**Comment by benwatson528** [comment]
Hello I have fixed this, look out for an upgrade prompt to 3.1.0 in the next couple of days.
