### ISSUE TITLE
Requires "parquet" in the file name

### ISSUE THREAD

**Issue by shasdemir** [benwatson528/intellij-avro-parquet-plugin#102]
Thank you for this nice plugin.

Many systems that create Parquet files do so without a full *.parquet file extension and with an illegible, UUID file name. For example: https://stackoverflow.com/questions/62200020/why-would-spark-insertinto-not-write-parquet-files-with-a-parquet-extension

Requiring the input file name to include "parquet" makes the user rename the file.

macOS 10.15
IntelliJ 2022.2.3

**Comment by benwatson528** [comment]
That sounds sensible, I'll happily accept a PR along those lines.

**Comment by benwatson528** [comment]
Hello I have fixed this, look out for an upgrade prompt to 3.1.0 in the next couple of days.
