### ISSUE TITLE
Avro files hangs Pycharm and Intellij

### ISSUE THREAD

**Issue by kevinashaw** [benwatson528/intellij-avro-parquet-plugin#105]
We are using Avro to store datasets.  The files are 400-600kB in size.  When I drag-n-drop them into either application, they either hang immediately (on import) or they complete the import and then hang when I try to look at the data.  My usual practice is to import the data, show it in Raw view (which is really JSON), select all of the data, copy it and then use a JSON viewer so I can see the data in a prettified JSON view (usually jsonlint.com).  However, I can no longer even select the data.  Double-clicking on the JSON data just hangs Pycharm/IntelliJ.
I did get a complaint about insufficient heapsize (was 2048MB) so I increased it (to 4096MB).  But with no improvement.
I tried to upload a file here, but Avro is not an approved data type.  I am attaching a [link](https://drive.google.com/file/d/1ppEESeLRhGgyhm_8o-foTQy2WPWpdlSr/view?usp=share_link) to a Google Drive file (let me know when/if it is downloaded, so I can retract link access after you get it).

Files are written as follows:
```
schema = avro.schema.parse(open("my_schema.avsc", "r").read())  # type: avro.schema.Schema
with DataFileWriter(open(filepath, "wb"), DatumWriter(), schema, codec="deflate") as writer:
    for example_avro in examples:
        writer.append(example_avro)
writer.close()
```

Below are details for the hardware, IntelliJ and PyCharm.

System: MacOS 12.2 on MBP16/M1/64MB

IntelliJ IDEA 2022.2.4 (Ultimate Edition)
Build #IU-222.4459.24, built on November 22, 2022
Runtime version: 17.0.5+7-b469.71 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    uk.co.hadoopathome.intellij.avro.intellijavroviewer (3.1.0)
    org.intellij.plugins.hcl (222.4459.16)
    net.sf.opk.avro-schema-support (213.2.1)
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    Statistic (4.2.6)
    InnerBuilder (1.3.0)
    mobi.hsz.idea.gitignore (4.4.2)
    com.atlassian.bitbucket.references (2022.1.214)
    io.snyk.snyk-intellij-plugin (2.4.46)
    com.intellij.bigdatatools (222.3345.33)

Kotlin: 222-1.7.21-release-272-IJ4167.29

PyCharm 2022.3 (Professional Edition)
Build #PY-223.7571.203, built on November 30, 2022
Runtime version: 17.0.5+1-b653.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    net.sf.opk.avro-schema-support (213.2.1)
    uk.co.hadoopathome.intellij.avro.intellijavroviewer (3.1.0)
    org.intellij.plugins.hcl (223.7571.175)
    com.atlassian.bitbucket.references (2022.1.220)
    ru.meanmail.plugin.requirements (2022.4)

**Comment by kevinashaw** [comment]
I will note that the following code is able to read and display the Avro file.  So I know the format is correct.
```
reader = DataFileReader(open(filepathname, "rb"), DatumReader())
records = [segment for segment in reader]
reader.close()

record = records[0] if records else []

pp = pprint.PrettyPrinter(depth=4)
pp.pprint(record)
```

**Comment by benwatson528** [comment]
Hello I don't have access to this file.

**Comment by kevinashaw** [comment]
I've enabled access.  Let me know when you get it. Thanks.

**Comment by kevinashaw** [comment]
@benwatson528 Did you want to access the file?

**Comment by benwatson528** [comment]
Hi Kevin I'm quite busy at the moment, it probably won't be this side of Christmas.

**Comment by benwatson528** [comment]
The plugin is basically just a wrapper around `org.apache.parquet:parquet-avro:1.12.3` and has unit tests so you could run your file in a unit test and see what error you get, see https://github.com/benwatson528/intellij-avro-parquet-plugin/blob/master/src/test/java/uk/co/hadoopathome/intellij/viewer/fileformat/AvroFileReaderTest.java.

**Comment by kevinashaw** [comment]
Hi Ben.  As mentioned, the file ingests correctly using the standard Avro python frameworks.  The only place the file has trouble is in this plugin.  I'm just posting this issue to let you know that there is a problem. I leave it up to you if you want to address it.  But if you do, let me know and I will reenable access to the file for a day so you can download.  -K

**Comment by benwatson528** [comment]
![image](https://user-images.githubusercontent.com/6214761/210212638-5951d1fa-aea3-4180-b441-8a7161598e0c.png)

**Comment by kevinashaw** [comment]
File access enabled.  Please let me know when you have downloaded the file, so I can disable it.  Thanks.

**Comment by benwatson528** [comment]
I increased IntelliJ's memory to 8GB and it loaded in about 10s on my PC. The file contains a single row that is almost 3,000,000 characters long when parsed as raw JSON.

The plugin uses https://github.com/wnameless/json-flattener to flatten JSON into a tabular format and I could see that taking the bulk of this time for such a wide dataset.

**Comment by kevinashaw** [comment]
Thank you.  I'm grateful for your help.  We use Avro as our primary data export and storage format so some of the files can get large.  Though these are normally only 0.5 MB, which doesn't seem too bad.  Thank you for your help.
