### ISSUE TITLE
Support brotli compressed Parquet file

### ISSUE THREAD

**Issue by Hongbo-Miao** [benwatson528/intellij-avro-parquet-plugin#106]
I saw this ticket https://github.com/benwatson528/intellij-avro-parquet-plugin/issues/96. In my case, I am on macOS.

Currently it shows nothing for [brotli](https://github.com/google/brotli) compressed Parquet file.
<img width="762" alt="image" src="https://user-images.githubusercontent.com/3375461/227043143-2dc68853-d0b2-4674-a785-cea28e0a52aa.png">

Attached are example Parquet files generated by API like `dataframe.to_parquet("myfile-brotli.parquet", engine="pyarrow", compression="brotli")`:

- [myfile-gzip.parquet.zip](https://github.com/benwatson528/intellij-avro-parquet-plugin/files/11044931/myfile-gzip.parquet.zip) (Can view successfully)
- [myfile-brotli.parquet.zip](https://github.com/benwatson528/intellij-avro-parquet-plugin/files/11044906/myfile-brotli.parquet.zip) (Cannot view)

It would be great to support, thanks! 😃

**Comment by benwatson528** [comment]
Hello, there's been no movement on this from elsewhere so there's nothing I can do here.

**Comment by Hongbo-Miao** [comment]
I assume your "no movement on this from elsewhere" means https://github.com/benwatson528/intellij-avro-parquet-plugin/issues/96#issuecomment-1073281471

> The plugin contains the Brotli compression class now, but it needs to find the Brotli native library on the host machine to be able to process the file. There are a few libraries out there but none have been updated in the last few years.

Thanks for the update!
