### ISSUE TITLE
Hello Can I get some help? about connection to parquet files

### ISSUE THREAD

**Issue by djj999** [benwatson528/intellij-avro-parquet-plugin#109]
How are you? 

I'm not familiar with code world. 

I installed the viewer on my Pycharm(community ver). I can see the plugin at the right side button. And the parquet file can be open to drag them on the plugin window. But when I double click the parquet file it doesn't open. And there is question mark before file name. 

How can I solve this?

**Comment by benwatson528** [comment]
Hello please could you attach some screenshots showing what you're trying
to do? You should be able to drag a file and have it load, and there should
be an error popup if that fails.

**Comment by djj999** [comment]
Oh, Thank you so much for quick your reply.

I can see the content of parquet files on the plugin window. 

But what I'd like to is that when I double click on parquet file opening the file on plugin window.

 

the plugin window doesn't open when I do double click the files.
And there is no error popups.
Is it normal right? or wrong? 

Could you help me? 



-----Original Message-----

**Comment by benwatson528** [comment]
> But what I'd like to is that when I double click on parquet file opening the file on plugin window.

I don't think that's possible - you can't associate `.parquet` files with an IntelliJ plugin. You have to drag and drop.

**Comment by djj999** [comment]
That's not possible. Alright. Thank you so much. 

-----Original Message-----
