### ISSUE TITLE
Read parquet file compressed with snappy

### ISSUE THREAD

**Issue by bioinfornatics** [benwatson528/intellij-avro-parquet-plugin#20]
Dear I am using pycharm 2019.3.3

once my project loaded from pycarm if I double click on *.parquet or *.parquet.snappy the binary file is open from an external text tool (gedit)

How to display parquet file using your plugins ?

Thanks for your plugin

Best regards

**Comment by benwatson528** [comment]
Hello, the plugin creates a Tool Window that should appear at the bottom of your IDE (or can be opened via the menu bar otherwise). You can then drag `.avro` and `.parquet` files into it.

**Comment by bioinfornatics** [comment]
@benwatson528 thanks for your quick help :-) 
Indeed that works for file which end with parquet but not for *.parquet.snappy

On linux it st possible to use magic file to guessing the fyle type:
```
 $ file  example.parquet.snappy 
example.parquet.snappy: Apache Parquet
```

Maybe that could be an enhancement

**Comment by benwatson528** [comment]
If you remove the ".snappy" from the end then is it successfully read?

**Comment by bioinfornatics** [comment]
yes that works. The tool guess the tfile type using file extension not its magic number.

**Comment by benwatson528** [comment]
Well I guess I have nothing better to do during quarantine :p. Time to dive into the murky world of Java's magic number handling.

**Comment by benwatson528** [comment]
I've uploaded the changes to IntelliJ, it might take a day or two to be accepted. Let me know if it works for you.

**Comment by benwatson528** [comment]
@bioinfornatics the changes have approved and the plugin is now live - you should get a prompt to update next time you open Pycharm.
