### ISSUE TITLE
Data editing 

### ISSUE THREAD

**Issue by zachary-povey** [benwatson528/intellij-avro-parquet-plugin#40]
Hey - loving this tool! Just wandering if you'd thought about the possibility of extending it to be an actual file editor as well as viewer and what work might be involved?

**Comment by benwatson528** [comment]
Thanks for the kind words Zach. I don't have any plans to add editing functionality; I'm happy with the plugin working purely as a lightweight viewer.

Editing would require a lot of work and several potentially tricky situations to be handled:
 - Validating that any updates are valid, 
 - Handling complex types, 
 - Supporting new elements in lists, 
 - Supporting nesting, 
 - Allowing schemas to be changed, 
 - Creating a new UI layout. 

Of course none of these are rocket science and anyone is welcome to fork my repo and use it as a base for creating an editor, but it's not something that I'll be working on.
