### ISSUE TITLE
Plugin not working with 2020.3 GoLang GO-203.4203.25 or IntelliJ

### ISSUE THREAD

**Issue by xmlking** [benwatson528/intellij-avro-parquet-plugin#47]
8:32 AM	Plugin error: Plugin 'Avro and Parquet Viewer' (version 'null') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is GO-203.4203.25

**Comment by benwatson528** [comment]
I'm not sure entirely what's going on here - I don't specify version restraints in my plugin, so it should be compatible  and I haven't seen issues like this with version bumps in the past.

I just ran a compatibility check vs the latest version of GoLang and the IntelliJ Plugin Verifier says that it should be compatible. Not that you should need to, but have you tried uninstalling and re-installing the plugin?

![image](https://user-images.githubusercontent.com/6214761/94945391-7fe09500-04d2-11eb-8092-8bcf7a1d1b7b.png)

**Comment by IamSandeepSahu** [comment]
_Plugin 'Protocol Buffer Editor' (version '2.2.1') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is GO-211.7142.13_

How did you resolve this error?

**Comment by benwatson528** [comment]
The plugin is compatible with every JetBrains IDE version released since 2017. Do you have a problem?
