### ISSUE TITLE
incompatible for new version of IDEA

### ISSUE THREAD

**Issue by HakChealKim** [benwatson528/intellij-avro-parquet-plugin#50]
as title.
				Plugin 'Avro and Parquet Viewer' (version 'null') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.5981.155

**Comment by benwatson528** [comment]
Try re-installing the plugin, there is no version 'null'. The latest version is 2.1.0.

**Comment by benwatson528** [comment]
I'm getting this too - looking into it. I don't specify an upper bound on the plugin version so there is no reason why it should be incompatible.

**Comment by benwatson528** [comment]
https://github.com/JetBrains/gradle-intellij-plugin/issues/574

**Comment by benwatson528** [comment]
A fix should be live on the marketplace in the next day or so and you should be prompted to update the plugin.

**Comment by benwatson528** [comment]
This is now live, and there shouldn't be issues with future versions.
