### ISSUE TITLE
Drag and drop does not work under ubuntu

### ISSUE THREAD

**Issue by jimwrightcz** [benwatson528/intellij-avro-parquet-plugin#54]
I think it is probably because I am a linux user but whenever I see "Simple drag-and-drop interface" I get a bad feeling. Therefore I am not surprised when it fails to work. Maybe the plugin is fine but drag and drop is not working the same as it does on the OS where you developed the plugin. However, my suggestion is never assume it will work because it is a little bit clever, perhaps unnecessarily so as a conventional file open dialog is also pretty simple, a little less clever and never fails to work in my experience. I tried:

1 Use the IDEs open dialog and either drag from the dialogue or open the containing directory and drag from there
2 Open as a text file, ignore the suggestion that the encoding is wrong and drag the files tab
3 Add the file to favourites and drag from there

BTW in 2 I am a little surprised that the plugin does not automatically configure the IDE to display .avro files this way (not as text but as AVRO) as if for edit, but I am not sure of the spec, so fair enough. 

IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-126-generic

**Comment by jimwrightcz** [comment]
I just found issue #41 relating to my BTW comment

**Comment by benwatson528** [comment]
The drag-and-drop functionality is provided by generic Java Swing methods and each release is tested against Ubuntu, Mac and Windows. The plugin is actually primarily developed on Ubuntu. I have not implemented any OS-specific functionality, and I suggest that you don't assume which operating system I test on.

In the interest of simplicity, I am not interested in adding a file open dialog.

Not that it should make a difference, but might I suggest updating IntelliJ?

**Comment by jimwrightcz** [comment]
OK Ben thanks for the info and suggestion.
