### ISSUE TITLE
Parquet timestamp columns not showing expected dates

### ISSUE THREAD

**Issue by jeanmarc** [benwatson528/intellij-avro-parquet-plugin#58]
I am trying to view parquet files that contain timestamp columns, using your plugin. The columns are reported as type = bytes, and do not show the expected date/time, but some garbled bytes.
When I read the parquet file in my application and print the column contents, the output shows the correct dates:
```
    val org = sparkSession.read.parquet(s"$rootDir/ORG")
    org.select("ACT_DTS", "REL_ID", "LGL_STC_TP_GGM_CODE").show()

    +-------------------+----------------+-------------------+
    |            ACT_DTS|          REL_ID|LGL_STC_TP_GGM_CODE|
    +-------------------+----------------+-------------------+
    |2021-01-01 00:00:00|ybZorkicohGtqiuD|                 CV|
    |2021-01-01 00:00:00|pfbiboglqpUaidcm|                VOF|
    |2021-01-01 00:00:00|dgafOmyrnFVrhcap|                 BV|
    +-------------------+----------------+-------------------+
```

![image](https://user-images.githubusercontent.com/2722081/105161189-614dea80-5b11-11eb-9454-631fcc59018b.png)

Is this the expected behavior?

**Comment by jeanmarc** [comment]
The timestamp column ACT_DTS is created in my code using a cast to go from the original string column:
```
      df.withColumn("ACT_DTA", unix_timestamp(df("ACT_DTS")).cast(TimestampType))

```

**Comment by benwatson528** [comment]
I'm afraid so - Parquet's relationship with timestamps is inconsistent at best. In this case the timestamps will be stored as INT96, which is no longer supported by Parquet. To avoid the entire file read failing I simply [print the bytes](https://github.com/benwatson528/intellij-avro-parquet-plugin/blob/f0c5edfa064d05d7a5a3e5e7153db94d42055d69/libs/README.md) of INT96 columns .

You will be able to get dates to display correctly if you change how the data is written ([see here](https://stackoverflow.com/questions/56582539/how-to-save-spark-dataframe-to-parquet-without-using-int96-format-for-timestamp)), but I appreciate that this isn't always possible:
```
spark.conf.set("spark.sql.parquet.outputTimestampType", "TIMESTAMP_MICROS")
```

**Comment by jeanmarc** [comment]
Thanks for the info. Using your suggested setting works for me.

**Comment by benwatson528** [comment]
Hello, INT96 columns now display correctly.
