### ISSUE TITLE
Parquet file viewer locks the file

### ISSUE THREAD

**Issue by jithing30** [benwatson528/intellij-avro-parquet-plugin#59]
Parquet files viewed cannot be deleted in windows as it throws error "File in use". I do not see any option to close the opened file from the Parquet Viewer.

So workaround will be drop in another file and continue with recreating parquet or deleting the file

**Comment by benwatson528** [comment]
Hello,

This will be a good feature to have. I won't have time this weekend so I'm happy for you (or anyone else) to address it, else I'll pick it up in a couple of weeks. It shouldn't be anything too difficult.

Ben

**Comment by benwatson528** [comment]
I can't recreate this - any file loaded into the plugin is parsed within a [`try` block](https://github.com/benwatson528/intellij-avro-parquet-plugin/blob/master/src/main/java/uk/co/hadoopathome/intellij/viewer/fileformat/ParquetFileReader.java#L36) that implements `Closeable` and so immediately closes the file after it's done reading the selected number of records.

Do you have an example file that you could share or any more information about how to recreate this?

Ben

**Comment by benwatson528** [comment]
Hi @jithing30, release 2.4.0 will be in the IntelliJ marketplace sometime over the next day or two - please let me know if this has resolved the issue for you.

**Comment by benwatson528** [comment]
Hi @jithing30, this is now live on the IntelliJ marketplace so please do update and let me know if it's resolved the issue.
