### ISSUE TITLE
Avro .parquet file: "Table" display visualisation broken

### ISSUE THREAD

**Issue by MarineMiquet** [benwatson528/intellij-avro-parquet-plugin#67]
Hi,

I am working on .parquet file generation and visualizing them in your plugin. 
I recently added one small change in the datatype of one column my .parquet file generation and since then is has been impossible to select the 'Table' display option. It's not really blocking since the 'raw' view still works, but it's still weird.

The change I made wad: switching my date column type from 'string' to 'long' with a logical type of 'timestamp-millis'.

I am forwarding the example of the working/not working files, could you look at this and tell me if the error is on my side or not ?
Thanks a lot

[github_issue_table_parquet.zip](https://github.com/benwatson528/intellij-avro-parquet-plugin/files/6323912/github_issue_table_parquet.zip)

Marine.

**Comment by benwatson528** [comment]
Hi Marine,

Sadly this is a limitation of the Parquet reading library. When passed a `timestamp-millis` column (or any other logical type), the `toString()` method doesn't add double quotes around the value, meaning it's not valid JSON and so can't be parsed.

I've raised this in the past (https://stackoverflow.com/questions/63655421/) and the answer appears to be "write your own Parquet reader" - something I don't want to do as it increases the complexity and risk of errors in the plugin, but I will revisit this and take a look.

Thanks,

Ben

**Comment by MarineMiquet** [comment]
Hi,

Thank you for your quick answer ! I was afraid that it would indicate a somehow corrupted file; but if it's only a reader limitation I can keep on working with this for now. 

Have a nice day !

**Comment by MarineMiquet** [comment]
Hi Ben !

Updated this morning and it's 'kinda' working ! the 'array' display is now available !
It's just that the date format seems wrong, in this example i have dates around 1st of May 2021, and I see them displayed in the year 53300:

![image](https://user-images.githubusercontent.com/5602628/116980831-0490cd00-acc7-11eb-8933-dc8cbad737af.png)
![image](https://user-images.githubusercontent.com/5602628/116981616-0d35d300-acc8-11eb-9d34-7a65378ea499.png)

I am using a timestamp with '"logicalType" : "timestamp-millis"' and it just seems that it displays a timestamp format without milliseconds, the logical type is ignored (when I add three 0 to my timestamp i get the year 53300 in currentmillis.com)

Apart from that it does work better :)

Have a nice day, and thay you for the quick update !
Marine

**Comment by benwatson528** [comment]
Thanks again Marine, I have fixed `timestamp-millis` and the update should be live in the next couple of days.

**Comment by MarineMiquet** [comment]
It's all good ! Thanks a lot for beeing so reactive !
