### ISSUE TITLE
Display total number of records

### ISSUE THREAD

**Issue by ybonillo** [benwatson528/intellij-avro-parquet-plugin#73]
It would be nice to have the total number of records without actually showing them all in the window since the display of all the records could crash the editor.  
`Displaying 1000 records of 123456 from /path/to/file.avro`  

NB : Very usefull tool to check easily content files... Thx for that ! 👍

**Comment by benwatson528** [comment]
Thanks this is a great suggestion. I'll look into implementing it in the next week or so.

**Comment by benwatson528** [comment]
This change is now live on the marketplace so you should be prompted to update the plugin via your IDE.
