### ISSUE TITLE
Unable to read int96  

### ISSUE THREAD

**Issue by klevis** [benwatson528/intellij-avro-parquet-plugin#87]
Error Message:

**INT_96 us deprecated. As interim enable read_int96_as_fixed flag to read as byte array**

From what I see the solution would be to set the **parquet.avro.readInt96AsFixed** property with the value "true" 

Can this be possible to set through intelij ?

**Comment by benwatson528** [comment]
Hello, sadly this is a known issue in the underlying library that reads Parquet files - see https://github.com/benwatson528/intellij-avro-parquet-plugin/issues/78 (specifically [my last comment](https://github.com/benwatson528/intellij-avro-parquet-plugin/issues/78#issuecomment-932912423)).

**Comment by klevis** [comment]
Thank you for the response , it seems I need to find alternative to int96.
