### ISSUE TITLE
No default file associated with .parquet

### ISSUE THREAD

**Issue by multimeric** [benwatson528/intellij-avro-parquet-plugin#90]
If I create a `.parquet` file with this plugin installed, it does not automatically have a file association:

![image](https://user-images.githubusercontent.com/5019367/156292897-a57a8fcb-5786-40b4-a0a4-6051137159fb.png)

If I try to use the right click → "Associate with File Type" dialogue, parquet doesn't come up as an option:
![image](https://user-images.githubusercontent.com/5019367/156292951-c587ddbb-7874-48f0-befa-bd09a7b268bf.png)

However, right click → "Override File Type" does work, but I have to do this manually for each file
![image](https://user-images.githubusercontent.com/5019367/156293009-690bc1d5-b1b3-4b11-8006-44d1398a08ea.png)

**Comment by benwatson528** [comment]
Hello, this plugin provides a tool window to let you drag and drop Avro and
Parquet files and visualise them. There's not file type association as they
can't be opened in the main editor.

**Comment by multimeric** [comment]
That's why I'm confused. I certainly have your plugin installed. Are you sure you can't right click → "Override File Type"? I'm on PyCharm professional fwiw.

**Comment by benwatson528** [comment]
Oh that's funny, thanks for pointing it out. I'd tried the Big Data Tools plugin when it first came out and couldn't get anything useful out of it. I must have completely missed the bit where it supports Parquet files. RIP this plugin I guess 😢
