### ISSUE TITLE
Parquet Column Names with Invalid AVRO Characters

### ISSUE THREAD

**Issue by jtmorelo** [benwatson528/intellij-avro-parquet-plugin#98]
This plugin appears to use avro to read parquet files but avro's valid name characters do not allow for "." to appear in a column name.  Parquet however, does not have this restriction.

Note that the parquet table.flatten() [api ](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.flatten) will flatten a struct field in a parquet file and add "." to column names.  This plugin will flag such columns with an error:

Error: Unable to process file, see IDEA logs for more information.  
Error: Illegal character in: parent.child

We like using this plugin.  Are there any plans to fix this issue in the future?

**Comment by benwatson528** [comment]
Hello, please see https://github.com/benwatson528/intellij-avro-parquet-plugin/issues/79. I'd love to be able to use the PyArrow library to read Parquet files instead of `parquet-avro` but last time I checked there wasn't a Java API.

Regards,

Ben
