### ISSUE TITLE
Support for byte data type

### ISSUE THREAD

**Issue by amymyo** [benwatson528/intellij-avro-parquet-plugin#99]
It's a great tool to view the avro data. But byte data types are not deserialized correctly, they're showing as `java.nio.HeapByteBuffer[pos=0 lim=4 cap=4]` for field values.

**Comment by benwatson528** [comment]
Hello, I'm not sure how you'd expect to see bytes as they don't really have a plaintext representation. This plugin uses [`parquet-avro`](https://github.com/apache/parquet-mr/tree/master/parquet-avro) for parsing data, you might want to look into that and see how it handles byte values.
